### ISSUE TITLE
الشاشة الرئيسية لجوريلا بها العقود الغير مكتملة مكتوب امامها انها مكتملة والعقود المكتملة اختفى منها (اسم تشكيلة الإنتاج)

### ISSUE THREAD

**Issue by engsheref** [engsheref/ATMS#10]
مثال من 
ATTMS
![image](https://github.com/user-attachments/assets/a25bbc6a-ff3d-4844-9a13-40f2a2d50925)

والموجود في
Gorilla
![image](https://github.com/user-attachments/assets/b53c8210-5fac-4acf-a4ac-9b0333ba1126)

**Comment by Mohaamaad7** [comment]
تم الحل

**Comment by engsheref** [comment]
تسلم
