### ISSUE TITLE
 استفسار لماذا لم يظهر نوع القماش والبراند في رأس التقرير الرئيسي  ولم يظهر القماش فقط في تقرير المرياجات والاكسسوارات والياقة والاساور ولكن ظهر نوع القماش والبراند في تقرير الأقمشة

### ISSUE THREAD

**Issue by engsheref** [engsheref/ATMS#3]
![image](https://github.com/user-attachments/assets/6c771f29-eb50-491f-9368-2784961ba89f)
![image](https://github.com/user-attachments/assets/ac9065a8-a20a-4dbe-8a31-37a29eb3490e)

https://gorilla.areyada.com/report_main.php?id=3

![image](https://github.com/user-attachments/assets/d9b81126-5746-467e-862a-66037c245c06)

وفي حالة أن الأوردر به اكثر من نوع قماش أي الانواع يجب أن يظهر في رأس الصفحة

أم نلغي هذا السطر بالكلية؟

مطلوب توحيد مصدر رأس التقرير لكل التقارير

![image](https://github.com/user-attachments/assets/36424709-acb6-41bb-ac71-e061e6d365ee)

https://gorilla.areyada.com/report_merges.php?id=3

على الرقم من ظهور نوع القماش والبراند في تقرير الاقمشة

![image](https://github.com/user-attachments/assets/00fb1848-cc4f-4a57-8b6e-92215bf017b7)

**Comment by Mohaamaad7** [comment]
بناء على الاتفاق
تم ازالة القماش من الهيدر
و تم حل باقي المشاكل

يمكنكم الفحص @engsheref

**Comment by engsheref** [comment]
بارك الله لك
أخي وحبيبي
