### ISSUE TITLE
توسيط بيانات في رأس التقرير ودراسة تعديل راس التقرير لتقليل ارتفاعه

### ISSUE THREAD

**Issue by engsheref** [engsheref/ATMS#5]
![image](https://github.com/user-attachments/assets/44f142ba-29d2-4b5f-8df1-0531f8f0cc0a)

**Comment by Mohaamaad7** [comment]
في مكتبة ال pdf يوجد خيارين cell و multicell 

الفرق بينهم ان cell يدعم المحاذاة الافقية و الرأسية لكن multicell لا يدعم المحاذاة الرأسية

لماذا نستخدم multicell في البراند و اسم العميل؟

لانه مسبقا كان اسم العميل اكبر من حجم الخليه فكان لابد من تفعيل اختيار wrap text و هذا ما لا يتوفر للاسف في خاصية cell 

انا قمت بتغيير ال multicell ل cell بشكل مؤقت لحين تسجيلهم لعملاء و براندات ذات اسماء طويلة

و بخصوص ارتفاع الهيدر انا قللته حاجة بسيطة

**Comment by engsheref** [comment]
تسلم
