### ISSUE TITLE
تعديل مسمى 

### ISSUE THREAD

**Issue by engsheref** [engsheref/ATMS#7]
استبدال الاسم الحالي
فضلا اختر (المجموعة اللونية) المرياج
إلى 
فضلا اختر (مجموعة لونية أو اكثر بالضغط على Ctrl واختيار أكثر من مجموعةلونية) المرياج
Please select (one or more color group by pressing Ctrl and selecting more than one color group)

**Comment by Mohaamaad7** [comment]
تم مع بعض التصرف من أجل اختصار الاسم

يمكنك تغيير ما تشاء من مسميات من خلال 

https://gorilla.areyada.com/lang/

و متغير العبارات المذكرة آنفاً هو 

**select_colors_group**

**Comment by engsheref** [comment]
ياااه انا كنت نسيت الصفحة الجميلة دي
حبيبي
