### ISSUE TITLE
نحتاج إظهار اسم تشكيلة الإنتاج كعمود إضافي في إحصائيات الرئيسية كذلك في جدول استعراض الاوردرات

### ISSUE THREAD

**Issue by engsheref** [engsheref/ATMS#8]
![image](https://github.com/user-attachments/assets/3bebe5c6-8cc1-463e-a78f-9e2a0ab3fd2f)

من البيانات العامة للأوردر
![image](https://github.com/user-attachments/assets/fff89671-f8b9-4706-8701-4ee9bb81275f)

![image](https://github.com/user-attachments/assets/5986f8c0-8f81-4dd2-8898-26d5686aaef7)

**Comment by Mohaamaad7** [comment]
تمت بفضل الله
ارجو المراجعة

**Comment by engsheref** [comment]
Magnificent
magnificent
